# Generated by Django 4.2.11 on 2024-05-13 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit', models.CharField(max_length=255, verbose_name='Commit')),
                ('branch', models.CharField(max_length=255, verbose_name='Branch')),
                ('status', models.CharField(max_length=255, verbose_name='Status')),
                ('deployed_at', models.DateTimeField(auto_now_add=True, verbose_name='Deployed At')),
                ('deployment_url', models.URLField(verbose_name='Deployment URL')),
                ('deployment_logs', models.TextField(blank=True, null=True, verbose_name='Deployment Logs')),
                ('build_command', models.CharField(blank=True, max_length=255, null=True, verbose_name='Build Command')),
                ('build_output', models.TextField(blank=True, null=True, verbose_name='Build Output')),
                ('deployed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployed_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Project Name')),
                ('visibility', models.CharField(choices=[('PU', 'Public'), ('PR', 'Private')], default='PU', max_length=255, verbose_name='Visibility')),
                ('repository_source', models.CharField(blank=True, max_length=255, null=True, verbose_name='Repository Source')),
                ('generated_domain', models.CharField(blank=True, max_length=255, null=True, verbose_name='Generated Domain')),
                ('technology_used', models.CharField(blank=True, max_length=255, null=True, verbose_name='Technology Used')),
                ('last_deployed', models.DateTimeField(blank=True, null=True, verbose_name='Last Deployed')),
                ('cloned_repo_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cloned Repository Path')),
                ('active_deployment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_deployment_for_project', to='projects.deployment')),
                ('collaborators', models.ManyToManyField(blank=True, related_name='collaborating_projects', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.AddField(
            model_name='deployment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='projects.project'),
        ),
    ]
