# Generated by Django 4.2.11 on 2024-05-13 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='deployment',
            table='deploymentss',
        ),
    ]
