# Generated by Django 4.2.11 on 2024-05-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_deployment_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deployment',
            name='deployment_url',
        ),
        migrations.AlterField(
            model_name='project',
            name='visibility',
            field=models.TextField(choices=[('PU', 'Public'), ('PR', 'Private')], default='PU', verbose_name='Visibility'),
        ),
    ]
