# Generated by Django 4.2.11 on 2024-05-13 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_deployment_deployment_url_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='deployment',
            table='deployments',
        ),
    ]
