# Generated by Django 4.2.11 on 2024-05-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_deployment_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='repository_source',
            new_name='git_repository',
        ),
        migrations.AddField(
            model_name='project',
            name='root_directory',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Root directory to run the project'),
        ),
    ]
