# Generated by Django 4.2.11 on 2024-05-16 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_rename_repository_source_project_git_repository_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deployment',
            name='build_command',
        ),
        migrations.RemoveField(
            model_name='deployment',
            name='deployed_by',
        ),
        migrations.RemoveField(
            model_name='project',
            name='collaborators',
        ),
        migrations.AddField(
            model_name='deployment',
            name='build_cmd',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Build Command'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='install_cmd',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Install Command'),
        ),
        migrations.CreateModel(
            name='environment_variables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, verbose_name='Key')),
                ('value', models.CharField(max_length=255, verbose_name='Value')),
                ('env_file', models.CharField(blank=True, default='.env', max_length=255, null=True, verbose_name='.env Filename')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environment_variables', to='projects.project')),
            ],
            options={
                'db_table': 'environment_variables',
            },
        ),
    ]
