# Generated by Django 4.2.11 on 2024-05-16 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_remove_deployment_build_command_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='environment_variables',
            new_name='EnvironmentVariables',
        ),
    ]
