# Generated by Django 4.2.11 on 2024-05-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_githubaccount_followers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sign_up_method',
            field=models.CharField(blank=True, default='email', max_length=255, null=True, verbose_name='login method used'),
        ),
    ]
