# Generated by Django 4.2.11 on 2024-05-05 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_image_user_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='github_accout',
            new_name='github_account',
        ),
    ]
