# Generated by Django 4.2.11 on 2024-05-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_github_accout_user_github_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubaccount',
            name='bio',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='githubaccount',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
