# Generated by Django 4.2.11 on 2024-05-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_user_github_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='github_username',
        ),
        migrations.AddField(
            model_name='user',
            name='github_access_token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='github access token'),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='github_installaton_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='github installaton_id'),
        ),
    ]
