# Generated by Django 4.2.11 on 2024-05-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_user_github_username_user_github_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='github_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='github id'),
        ),
    ]
