# Generated by Django 4.2.11 on 2024-05-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_github_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='github_access_token',
            new_name='github_public_access_token',
        ),
        migrations.AddField(
            model_name='user',
            name='github_private_access_token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='github private access token'),
        ),
    ]
