# Generated by Django 4.2.11 on 2024-05-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_rename_github_access_token_user_github_public_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='installed_github',
            field=models.BooleanField(default=False, null=True, verbose_name='is user installed github on his/her account'),
        ),
    ]
