# Generated by Django 4.2.11 on 2024-05-10 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_user_installed_github'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailverification',
            old_name='token',
            new_name='otp',
        ),
    ]
