# Generated by Django 4.2.11 on 2024-05-21 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_rename_token_emailverification_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='installed_github',
            new_name='connected_github',
        ),
    ]
